### ISSUE TITLE
prisma记录1

### ISSUE THREAD

**Issue by youwillbe** [youwillbe/blog#5]
## 1.前言
`prisma`将数据库`crud`操作映射成`graphql`的`api`，提供简化和类型安全的数据库访问，并能用`graphql`的`schema`声明式的创建数据模型，同时提供了可视化的数据管理工具，是强大的生产力工具。
## 2.启动`prisma`服务
首先安装`prisma`：
```
yarn global add prisma
```
接着需要安装好`docker`，可以去[docker官网](https://www.docker.com/get-started)寻找安装方式。
安装好之后准备一个目录，并新建名为`docker-compose.yml`的文件。`prisma`目前支持`MySQL`、`PostgreSQL`以及`MongoDB`这三种数据库，选择一个并写入相应的配置文件：
```
// MySQL
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```
```
// PostgreSQL
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```
```
// MongoDB
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
```
接下来运行命令：
```
docker-compose up -d
```
完成后prisma已经连接了docker里的数据库，并在`localhost:4466`运行了。
运行`docker ps`可以看到有两个容器在运行了：
![image](https://user-images.githubusercontent.com/16474244/56084255-0169e080-5e63-11e9-99c1-895d028dc94d.png)
## 3.创建数据模型
运行以下命令创建`prisma`的配置文件和示例数据模型文件：
```
prisma init --endpoint http://localhost:4466
```
```
// prisma.yml
endpoint: http://localhost:4466
datamodel: datamodel.prisma
```
```
// datamodel.prisma
type User {
    id: ID! @unique
    name: String!
}
```
如果使用`MongoDB`，需要做如下更改：
```
// prisma.yml
endpoint: http://localhost:4466
datamodel: datamodel.prisma
databaseType: document
```
```
// datamodel.prisma
type User {
  id: ID! @id
  name: String!
}
```
然后运行：
```
prisma deploy
```
部署我们的数据模型，完成之后就可以在`localhost：4466`中看到生成的`graphql api`了。
![image](https://user-images.githubusercontent.com/16474244/56084426-83f39f80-5e65-11e9-8a40-26f14b74d135.png)
当然，`prisma`不仅提供了`playground`这个类似`graphiql`的工具，在最近的版本中，也提供了一个可视化的数据管理工具` Prisma Admin`，可以在`localhost:4466/_admin`访问。
## 4.用`prisma client`读写数据
可以通过生成`prisma client`来简单的读写数据，添加如下配置到`prisma.yml`：
```
generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
```
然后运行：
```
prisma generate
```
接下来为运行读写，我们做一些准备。先安装下面的包：
```
yarn init -y
yarn add prisma-client-lib
```
然后新建`index.js`文件，并写入下面的内容：
```
import { prisma } from './generated/prisma-client'

async function main() {
  const newUser = await prisma.createUser({ name: 'Alice' })
  console.log(`Created new user: ${newUser.name} (ID: ${newUser.id})`)

  const allUsers = await prisma.users()
  console.log(allUsers)
}

main().catch(e => console.error(e))
```
然后运行我们的代码：
```
node index.js
```
可以看到我们成功往数据库插入了一个用户`Alice`，在`prisma admin`里面也可以清晰的看到。
当然，我们也可以进行其他的操作：
```
// 查询单个用户
const user = await prisma.user({ id: '__USER_ID__' })
```
```
// 过滤用户列表
const usersCalledAlice = await prisma.users({
    where: {
      name: 'Alice'
    }
})
```
```
// 更新用户信息
 const updatedUser = await prisma.updateUser({
    where: { id: '__USER_ID__' },
    data: { name: 'Bob' }
})
```
```
// 以及删除用户
 const deletedUser = await prisma.deleteUser({ id: '__USER_ID__' })
```

**Comment by YouWillBe** [comment]
## 2.启动`prisma`服务
首先安装`prisma`：
```
yarn global add prisma
```
接着需要安装好`docker`，可以去[docker官网](https://www.docker.com/get-started)寻找安装方式。
安装好之后准备一个目录，并新建名为`docker-compose.yml`的文件。`prisma`目前支持`MySQL`、`PostgreSQL`以及`MongoDB`这三种数据库，选择一个并写入相应的配置文件：
```
// MySQL
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```
```
// PostgreSQL
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```
```
// MongoDB
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
```
